/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'student_note';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String ANIMATION

  _

  1717493499899

  =

  '

  assets/animation/Animation - 1717493499899.json

  ';

  static const String BK11 = 'assets/images/bk11.jpg';
  static const String BK12 = 'assets/images/bk12.jpg';
  static const String BK13 = 'assets/images/bk13.jpg';
  static const String BK14 = 'assets/images/bk14.jpg';
  static const String BK15 = 'assets/images/bk15.jpg';
  static const String BK16 = 'assets/images/bk16.jpg';
  static const String BK17 = 'assets/images/bk17.jpg';
  static const String BK18 = 'assets/images/bk18.jpg';
  static const String BK30 = 'assets/images/bk30.jpg';
  static const String P1 = 'assets/images/p1.jpeg';
  static const String P2 = 'assets/images/p2.png';
  static const String P3 = 'assets/images/p3.jpg';
  static const String P4 = 'assets/images/p4.jpg';
  static const String P5 = 'assets/images/p5.jpg';
  static const String P6 = 'assets/images/p6.jpg';
  static const String P7 = 'assets/images/p7.jpg';
}
