// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaM2ONZ3SDUrXm4qVKWmEQl0rbCHmx5TM',
    appId: '1:1037501686902:android:bb94d069ceb025a0e7eb57',
    messagingSenderId: '1037501686902',
    projectId: 'uninote-b65b3',
    databaseURL: 'https://uninote-b65b3-default-rtdb.firebaseio.com',
    storageBucket: 'uninote-b65b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAMmH0CmIUN5Y3vxCGkDQbtwI99YWYuQo',
    appId: '1:1037501686902:ios:b50a97c65904df8be7eb57',
    messagingSenderId: '1037501686902',
    projectId: 'uninote-b65b3',
    databaseURL: 'https://uninote-b65b3-default-rtdb.firebaseio.com',
    storageBucket: 'uninote-b65b3.firebasestorage.app',
    iosBundleId: 'com.example.studentNote',
  );
}
